#!/bin/bash

wget https://ftp.gnu.org/gnu/gcc/gcc-7.5.0/gcc-7.5.0.tar.xz
wget https://ftp.gnu.org/gnu/gmp/gmp-5.1.3.tar.xz
wget https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
wget https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.6.tar.xz

wget https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.6.tar.bz2
